config/routes.rb
Rails.application.routes.draw do
  #API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  devise_for :users
  
  resources :candidates do 
    member do
      # put :vote, to: 'candidates#vote'
      put :vote #put /candidates/2/vote
    end  
  end

  root 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  validates :age, numericality: { greater_than: 40}
  #validates(:name, {prensence: true})
  has_many :vote_logs, dependent: :destroy
  has_many :users, through: :vote_logs
end

# rails g model Candidate ...

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vote_logs
  has_many :candidates, through: :vote_logs
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
  belongs_to :user
end

app/controllers/api/v2/candidates_controller.rb
class Api::V2::CandidatesController < ApplicationController

  def index
    @candidates = Candidate.all
    # render json: @candidates 
  end
  def show
    @candidate = Candidate.find_by(id: params[:id])
    # render json: @candidate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]

  def index
    @candidates = Candidate.all.order(vote: :desc).page(params[:page]).per(5)
  end

  def new 
    @candidate = Candidate.new
  end

  def create
    
    @candidate = Candidate.new(candidate_params)
    
    if @candidate.save
      # flash[:notice] = "新增候選人成功！"
      redirect_to root_path, notice: "新增候選人成功！"

    else
      # flash[:notice] = "UCCU"
      # redirect_to new_candidate_path
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    
    if @candidate.update(candidate_params)
      # flash[:notice] = "更新候選人成功！"
      redirect_to root_path, notice: "更新候選人成功！"
    else
      # flash[:notice] = "UCCU"
      # redirect_to new_candidate_path
      render :edit
    end
  end

  def destroy
    
    @candidate.destroy

    flash[:notice] = "資料刪除成功！"
    redirect_to root_path
  end

  def vote
    # @candidate.update(vote: @candidate.vote + 1)
    
    # vv = VotLog.new(candidate_id: @candidate.id, ip_address: request.remote_ip)
    # vv.save
    if user_signed_in?
      
      # VoteLog.create(candidate_id: @candidate.id, ip_address: request.remote_ip)
      # @candidate.votlogs.create(ip_address: request.remote_ip)
      if VoteLog.find_by(user: current_user, candidate: @candidate)
        message = "已投過此候選人"
      else
        current_user.vote_logs.create(candidate: @candidate, ip_address: request.remote_ip)
        message = "投票成功"
      end
      
      redirect_to root_path, notice: message
    else
      redirect_to root_path, notice: "請先登入會員"
    end
    
  end

  private

  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
  # Stonger params
  def candidate_params
    clean_params = params.require(:candidate).permit(:name, :age, :policy, :party, :degree)
  end

end

app/helpers/api/v2/candidates_helper.rb
module Api::V2::CandidatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
  <ul>
    <% candidate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= simple_form_for(candidate) do |form| %>
 
  <div class="box">
    <%= form.input :name, label: '姓名' %>
    <%= form.input :party, label: '黨派'%>
    <%= form.input :degree, label: '學歷'%>
    <%= form.input :age, label: '年齡'%>
    <%= form.input :policy, label: '政見'%>
    <%= form.button :submit, class: 'btn btn-md btn-success'%>
  </div>

  
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form', candidate: @candidate%>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>


<%= paginate @candidates, theme: 'twitter-bootstrap-4' %>
<% @candidates.each do |candidate|%>

  <li>
    <%= link_to '懇請賜票！！', vote_candidate_path(candidate.id), class: 'btn btn-md btn-warning', method:'put',data: { confirm: "R U SURE？", abd: 1234}%>
    <!-- (<%= candidate.vote_logs_count %>票) -->
    (<%= candidate.vote_logs_count %>票)
    <%= link_to candidate.name, candidate_path(candidate.id) %>
    <%= link_to '編輯', edit_candidate_path(candidate.id), class: 'btn btn-md btn-success' %>
    <%= link_to '刪除', candidate_path(candidate.id), {class: 'btn btn-md btn-danger', method:'delete',
         data: { confirm: "請確認？", abd: 1234} }%>
  </li>
<% end %>

<%= link_to '新增候選人', new_candidate_path, class: 'btn btn-primary btn-lg'  %>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render 'form', candidate: @candidate %>

<!-- parcial render -->

app/views/candidates/show.html.erb
<% if @candidate %>

  <h1> <%= @candidate.name %> </h1>
  <ul>
    <li>得票數：<%=@candidate.vote%></li> 
    <li>學歷：<%= @candidate.degree %></li>
    <li>年紀：<%= @candidate.age %></li>
    <li>黨派：<%= @candidate.party %></li>
    <li>政見：<%= @candidate.policy %></li>
  </ul>
<%else%>
  <h1>U can't see me</h1>
<% end %>

<%= link_to '候選人列表', candidates_path, class: 'btn btn-primary btn-lg'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivoting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './shared/frontend/navbar' %>
    <div><%= flash[:notice] %></div>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>

      <ul class="navbar-nav ">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "登出", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "註冊", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "登入", new_user_session_path, class: "nav-link"%>
          </li>
        <% end %>   
      </ul>

    
  </div>
</nav>